apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: demo-pacman
  description: A pacman service!
  tags:
  - backend
  - service
  annotations:
    argocd-url: https://openshift-gitops-server-openshift-gitops.apps.rosa-rm7ns.gkef.p1.openshiftapps.com/applications/pacman
    argocd/app-selector: 'default-gitops=pacman'
    jenkins.io/job-full-name: default-jenkins:pacman/pacman-pipeline
spec:
  type: service
  owner: jonas-team
  lifecycle: production
