kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongo-storage
  backstage.io/kubernetes-id: pacman-demo
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
