apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: mongo
    backstage.io/kubernetes-id: pacman-demo
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mongo
  template:
    metadata:
      labels:
        name: mongo
        backstage.io/kubernetes-id: pacman-demo
    spec:
      containers:
      - image: bitnami/mongodb:latest
        name: mongo
        ports:
        - name: mongo
          containerPort: 27017
        volumeMounts:
        - name: mongo-db
          mountPath: /data/db
      volumes:
      - name: mongo-db
        persistentVolumeClaim:
          claimName: mongo-storage
